### ISSUE TITLE
♻️ 리팩토링

### ISSUE THREAD

**Issue by youhyeoneee** [youhyeoneee/wanted-pre-onboarding-backend#15]
## 📌 Description
- 리팩토링을 진행합니다.

## 📝 To-do
- [x] 패키지 구조 정리
- [x] response 네이밍 통일
- [ ] 메서드명, 변수명 정리
- [ ] 불필요한 테스트 코드 제거 (참고 : https://youtu.be/qECd2q3USqA?si=uzQqOLEMEu0-eIRa)
- [ ] 로직 정리
